name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test

      - name: Deploy to server (optional)
        run: |
          echo "Deploy step will be added here."
        if: success()

  # Windows-specific configuration
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        java-version: [11]
        os: [windows-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install JDK 11 on Windows
        if: runner.os == 'Windows'
        run: |
          choco install openjdk11
          java -version

      - name: Cache Maven dependencies (Windows)
        uses: actions/cache@v3
        with:
          path: C:\Users\RunnerUser\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (Windows)
        run: mvn clean install

      - name: Run tests with Maven (Windows)
        run: mvn test
